remote_theme: McNative/jekyll-mcnative-theme
baseurl: https://github.com/McNative/McNative
title: McNative Documentation
url: test-docs.mcnative.org
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
